# Generated by Django 5.1.3 on 2024-11-30 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncios',
            name='titulo',
            field=models.CharField(default='Novo Anúncio', max_length=100),
            preserve_default=False,
        ),
    ]
